[general]
resolution = [1024, 1024]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "dataset/images"
cache_directory = "dataset/cache"
num_repeats = 1

