[general]
resolution = [1200, 1800] 
caption_extension = ".txt"
batch_size = 2
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "dataset_nhat_binh/images"
cache_directory = "dataset_nhat_binh/cache"
num_repeats = 10